fixup! fixup! httpkadmind: Add test!

diff --git a/tests/kdc/check-httpkadmind.in b/tests/kdc/check-httpkadmind.in
--- a/tests/kdc/check-httpkadmind.in
+++ b/tests/kdc/check-httpkadmind.in
@@ -199,22 +199,67 @@ get_keytab "dNSName=foo.ns.${domain}" -sf -o "${objdir}/extracted_keytab" &&
 hn=xyz.${domain}
 p=HTTP/$hn
 echo "Checking key rotation"
+rm -f extracted_keytab*
 grant dnsname $hn foo@${R}
 get_keytab "dNSName=${hn}" -sf -o "${objdir}/extracted_keytab" ||
     { echo "Failed to get a keytab for $p with curl"; exit 1; }
 ${ktutil} -k "${objdir}/extracted_keytab" list --keys > extracted_keytab.rest1 ||
     { echo "Failed to list keytab for $p"; exit 1; }
-get_keytab "dNSName=${hn}&rotate=true" -sf -o "${objdir}/extracted_keytab2" ||
+test "$(grep $p extracted_keytab.rest1 | wc -l)" -eq 1 ||
+    { echo "Wrong number of new keys!"; exit 1; }
+get_keytab "dNSName=${hn}&rotate=true" -sf -o "${objdir}/extracted_keytab" &&
+    { echo "GET succeeded for write operation!"; exit 1; }
+get_keytab "dNSName=${hn}&rotate=true" -X POST --data-binary @/dev/null -sf -o "${objdir}/extracted_keytab" ||
     { echo "Failed to get a keytab for $p with curl"; exit 1; }
-${ktutil} -k "${objdir}/extracted_keytab2" list --keys > extracted_keytab.rest2 ||
+${ktutil} -k "${objdir}/extracted_keytab" list --keys > extracted_keytab.rest2 ||
     { echo "Failed to list keytab for $p"; exit 1; }
-cmp extracted_keytab.rest1 extracted_keytab.rest2 &&
+cmp extracted_keytab.rest1 extracted_keytab.rest2 > /dev/null &&
     { echo "Keys for $p did not change!"; exit 1; }
+test "$(grep $p extracted_keytab.rest2 | wc -l)" -eq 2 ||
+    { echo "Wrong number of new keys!"; exit 1; }
+
+hn=xyz.${domain}
+p=HTTP/$hn
+echo "Checking key revocation"
+rm -f extracted_keytab*
+grant dnsname $hn foo@${R}
+get_keytab "dNSName=${hn}" -sf -o "${objdir}/extracted_keytab" ||
+    { echo "Failed to get a keytab for $p with curl"; exit 1; }
+${ktutil} -k "${objdir}/extracted_keytab" list --keys > extracted_keytab.rest1 ||
+    { echo "Failed to list keytab for $p"; exit 1; }
+get_keytab "dNSName=${hn}&revoke=true" -sf -o "${objdir}/extracted_keytab" &&
+    { echo "GET succeeded for write operation!"; exit 1; }
+get_keytab "dNSName=${hn}&revoke=true" -X POST --data-binary @/dev/null -sf -o "${objdir}/extracted_keytab" ||
+    { echo "Failed to get a keytab for $p with curl"; exit 1; }
+${ktutil} -k "${objdir}/extracted_keytab" list --keys > extracted_keytab.rest2 ||
+    { echo "Failed to list keytab for $p"; exit 1; }
+cmp extracted_keytab.rest1 extracted_keytab.rest2 > /dev/null &&
+    { echo "Keys for $p did not change!"; exit 1; }
+test "$(grep $p extracted_keytab.rest2 | wc -l)" -eq 1 ||
+    { echo "Wrong number of new keys!"; exit 1; }
+
+hn=abc.${domain}
+p=HTTP/$hn
+echo "Checking principal creation"
+rm -f extracted_keytab
+grant dnsname $hn foo@${R}
+get_keytab "dNSName=${hn}&create=true" -sf -o "${objdir}/extracted_keytab" &&
+    { echo "GET succeeded for write operation!"; exit 1; }
+get_keytab "dNSName=${hn}&create=true" -X POST --data-binary @/dev/null -sf -o "${objdir}/extracted_keytab" ||
+    { echo "Failed to get a keytab for $p with curl"; exit 1; }
+${ktutil} -k "${objdir}/extracted_keytab" list --keys > extracted_keytab.rest ||
+    { echo "Failed to list keytab for $p"; exit 1; }
+rm -f extracted_keytab
+${kadmin} ext_keytab -k extracted_keytab $p ||
+    { echo "Failed to get a keytab for $p with kadmin"; exit 1; }
+${ktutil} -k "${objdir}/extracted_keytab" list --keys > extracted_keytab.kadmin ||
+    { echo "Failed to list keytab for $p"; exit 1; }
+cmp extracted_keytab.kadmin extracted_keytab.rest ||
+    { echo "Keytabs for $p don't match!"; exit 1; }
 
 # TODO
 #
-#  - test more service names
-#  - test more write operations for concrete principals
+#  - test more service names, more namespaces
 #  - test materialization of virtual principals
 #  - test with kadmind instead of direct local HDB access
 #  - test with read-only kadmind and primary kadmind, and check that we
