bx509d: Add support for EdDSA (Ed255129, Ed448)

diff --git a/tests/kdc/check-bx509.in b/tests/kdc/check-bx509.in
--- a/tests/kdc/check-bx509.in
+++ b/tests/kdc/check-bx509.in
@@ -655,6 +655,61 @@ else
     exit 1
 fi
 
+echo "Making an Ed25519 CSR"
+csr_revoke
+$hxtool request-create  --subject='' --generate-key=ed25519 \
+                        --key=FILE:"${objdir}/k-ed25519.der" "${objdir}/req-ed25519" ||
+    { echo "Failed to make an Ed25519 CSR"; exit 2; }
+
+echo "Fetching a trivial user certificate with Ed25519 key"
+csr=$($rkbase64 -- ${objdir}/req-ed25519 | $rkvis -h --stdin)
+token=$(KRB5CCNAME=$cache $gsstoken HTTP@$server)
+if (set -vx; get_cert '' -sf -o "${objdir}/trivial-ed25519.pem"); then
+    $hxtool print --content "FILE:${objdir}/trivial-ed25519.pem"
+    # Check that the certificate has an Ed25519 public key
+    if openssl x509 -in "${objdir}/trivial-ed25519.pem" -noout -text | grep -q "Public Key Algorithm: ED25519"; then
+        echo 'Certificate has Ed25519 public key!'
+    else
+        echo 'FAIL: Certificate does not have Ed25519 public key'
+        exit 1
+    fi
+    if $hxtool acert --end-entity                                            \
+                    --expr="%{certificate.subject} == \"CN=foo,$DCs\""  \
+                    -P "foo@${R}" "FILE:${objdir}/trivial-ed25519.pem"; then
+        echo 'Successfully obtained an Ed25519 client certificate!'
+    else
+        echo 'FAIL: Obtained an Ed25519 certificate w/o expected PKINIT SAN)'
+        exit 1
+    fi
+else
+    echo 'Failed to get an Ed25519 certificate!'
+    exit 1
+fi
+
+echo "Fetching an Ed25519 server certificate with one dNSName SAN"
+csr_grant san_dnsname $server foo@${R}
+csr=$($rkbase64 -- ${objdir}/req-ed25519 | $rkvis -h --stdin)
+token=$(KRB5CCNAME=$cache $gsstoken HTTP@$server)
+if (set -vx; get_cert "&dNSName=$server" -sf -o "${objdir}/server-ed25519.pem"); then
+    $hxtool print --content "FILE:${objdir}/server-ed25519.pem"
+    # Check that the certificate has an Ed25519 public key
+    if openssl x509 -in "${objdir}/server-ed25519.pem" -noout -text | grep -q "Public Key Algorithm: ED25519"; then
+        echo 'Server certificate has Ed25519 public key!'
+    else
+        echo 'FAIL: Server certificate does not have Ed25519 public key'
+        exit 1
+    fi
+    if $hxtool acert --end-entity -D $server "FILE:${objdir}/server-ed25519.pem"; then
+        echo 'Successfully obtained an Ed25519 server certificate!'
+    else
+        echo 'Got a broken Ed25519 server certificate'
+        exit 1
+    fi
+else
+    echo 'Failed to get an Ed25519 server certificate!'
+    exit 1
+fi
+
 echo "Fetch TGT (not granted for other)"
 token=$(KRB5CCNAME=$cache $gsstoken HTTP@$server)
 if (set -vx;
